task1/signupin/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as authentication_views

app_name='signupin'

urlpatterns = [
    path("",views.homepage,name='homepage'),
    path("usertype/",views.usertyperview,name="usertype"),
    path("signup/",views.registerview,name='signup'),
    path("signin/",views.login,name='signin'),
    #path("signin/",authentication_views.LoginView.as_view(template_name='signin.html'), name="signin"),
    #path("logout/",authentication_views.LogoutView.as_view(template_name='typeofusers.html'),name="logout"),
    path("welcome/<str:name>/",views.homeview,name='welcome'),
    path("logout/",views.logoutview,name='logout'),
]

task1/task1/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('signupin.urls', namespace='signupin')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

task1/signupin/models.py
from django.db import models
from django.contrib.auth.models import User

class UTModel(models.Model):
    type=[('Patient','PATIENT'),('Doctor','DOCTOR')]
    usertype=models.CharField(max_length=20,choices=type, default='Patient')

class SignUpModel(User):
    ProfilePic=models.ImageField(upload_to='profilepic/')
    ConfirmPassword=models.CharField(max_length=100)
    Address=models.CharField(max_length=100)








task1/signupin/forms.py
from django import forms
from .models import SignUpModel,UTModel
from django.contrib.auth.hashers import make_password
from django.core.exceptions import ValidationError

class UserTypeForm(forms.ModelForm):
    class Meta:
        model=UTModel
        fields='__all__'
        labels={'usertype':'What Type of User You Are?'}
        user_types=[('Patient','Patient'),('Doctor','Doctor')]
        widget={'usertype':forms.RadioSelect(choices=user_types)}

class RegisterForm(forms.ModelForm):
    class Meta:
        model=SignUpModel
        fields=['first_name','last_name','ProfilePic','username','email','password','ConfirmPassword','Address']
    
    def clean(self):
        cleaned_data = super(RegisterForm,self).clean()
        password1=cleaned_data.get('password')
        password2=cleaned_data.get('ConfirmPassword')
        if password1 != password2:
            self.add_error('ConfirmPassword', "Password Mismatch")
        return cleaned_data
        


task1/signupin/views.py
from django.shortcuts import render,redirect
from .forms import UserTypeForm,RegisterForm
from django.urls import reverse
from django.contrib.auth import authenticate, login as auth_login,logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from .models import SignUpModel
from django.http import HttpResponse

def homepage(request):
    return render(request,"signupin.html")

def usertyperview(request):
    if request.method=='POST':
        form=UserTypeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('signupin:signup'))
    else:
        form=UserTypeForm()
    return render(request,"typeofusers.html",{'usertype_form':form})

def registerview(request):
    if request.method=='POST':
        form=RegisterForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect(reverse('signupin:signin'))
    else:
        form=RegisterForm()
    return render(request,'signup.html',{'register_form':form})

def login(request):
    if request.method=='POST':
        form=AuthenticationForm(request,request.POST)
        if form.is_valid():
            print('yes')
            username=request.POST['username']
            password=request.POST['password']
            user=authenticate(username=username,password=password)
            if user is not None:
                auth_login(request,user)
                name=user.get_username()
                url = reverse('signupin:welcome')
                print(url)
                return redirect(url)
    else:
        form=AuthenticationForm()
    return render(request,'signin.html',{'form':form,'name':name})


def homeview(request,name):
    data=SignUpModel.objects.get(username=name)
    return render(request,'welcome.html',{'data':data})


def logoutview(request):
    auth_logout(request)
    return redirect(reverse('signupin:usertype'))



task1/signupin/templates/homwel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome</h1>
</body>
</html>

task1/signupin/templates/signin.html
<!DOCTYPE html>
{% extends "index.html" %}
{% block title %}Sign In{% endblock %}
{% block body%}
<br><br><br>
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-dark">
                    <div class="card-title">
                        Login
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form%}
                        <div class="col-md-12 text-center">
                            <div class="form-group">
                                {{field.label_tag}}
                                {{field}}
                                <br><br>
                            </div>
                        </div>
                        {% endfor %}
                        <div class="col-md-12 text-center">
                            <button class= " btn btn-primary" type="submit">Login</button>
                        </div>
                        
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

task1/signupin/templates/signup.html
<!DOCTYPE html>
{% extends "index.html"%}
{% block title %}Sign Up{% endblock %}
{% block body%}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header text-white bg-dark">
                        <div class="card-title text-center">
                            Register
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% for field in register_form%}
                                <div class="form-group">
                                    {{field.label_tag}}
                                    {{field}}
                                    {{field.errors}}<br><br>
                                </div>
                            {% endfor %}
                            <div class="text-center"><button class= " btn btn-primary" type="submit">Register</button></div>
                        </form>
                        <p class="text-center">If you already have an account, <a href="{% url 'signupin:signin' %}">login</a> instead.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

task1/signupin/templates/signupin.html
<!DOCTYPE html>
{% extends "index.html"%}
{% block title %}Home Page{% endblock %}
{% block body%}
<br><br><br><br><br><br><br>
    <h1 class="text-center font-weight-bold text-warning">Welcome to the SignUpIn Application</h1>
    <br><br>
    <div class="row text-center">
            <div class="col-md-7">
                <a class="nav-item nav-link font-weight-bold text-dark" href="{% url 'signupin:usertype' %}">SignUp</a>
            </div>
            <div class="col-md-2">   
                <a class="nav-item nav-link font-weight-bold text-dark" href="{% url 'signupin:signin' %}">SignIn</a>
            </div>
    </div>
{% endblock %}

task1/signupin/templates/typeofusers.html
<!DOCTYPE html>
{% extends "index.html" %}
{% block title %}Type of Users{% endblock %}
{% block body%}
<br><br>
    <form method="POST">
        {% csrf_token %}
        {% for field in usertype_form %}
        <div class="container">
            <div class="row">
                <div class="card-body border-0 d-flex justify-content-center">
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>{{field}}
                        <label class="form-check-label" for="flexRadioDefault2">{{field.label_tag}}</label>
                    </div>
                </div>
            </div>
            <br><br>
            <div class="col">
                <div class="text-center">
                    <button type="submit" class="btn btn-success btn-lg">Enter</button>
                </div>
                <p class="text-center">If you already have an account, <a href="{% url 'signupin:signin' %}">login</a> instead.</p>
            </div>
        </div>
        {% endfor %}
        <br><br>
    </form>
{% endblock %}

task1/signupin/templates/welcome.html
<!DOCTYPE html>
{% extends "index.html" %}
{% block title %}Dashboard{% endblock %}
{% block body%}
    <h1 class="text-center">Welcome {{user.username}} to Your Dashboard</h1><br><br>
    <div class="container">
        <div class="row text-center">
            <div class="col-md-2 float-right">
                <img src="{{user.ProfilePic.url}}" alt="error" style="width:150px;height:150px;border-radius:60px">
            </div>
            <div class="col-md-8">
                <div class="col">
                    <h4>First Name: {{user.first_name}}</h4>
                    <h4>Last Name: {{user.last_name}}</h4>
                    <h4>Password: {{user.ConfirmPassword}}</h4>
                    <h4>Email ID: {{user.email}}</h4>
                    <h4>Address: {{user.Address}}</h4>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

task1/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</head>
<body style="background-image: linear-gradient(blue,white,purple);height:550px;">
    <nav class="navbar navbar-dark bg-secondary">
        <a href="{% url 'signupin:homepage' %}" class="navbar-brand">SignUpIn App</a>
            <div class="nav justify-content-center">
                <a class="nav-item nav-link text-white" href="{% url 'signupin:homepage' %}">Home</a>
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link text-white" href="{% url 'signupin:wel' %}">Dashboard</a>
                    <a class="nav-item nav-link text-white" href="{% url 'signupin:logout' %}">Logout</a>
                {% endif %}
            </div>
    </nav>
    {% block body %}
    {% endblock %}
</body>
</html>